### ISSUE TITLE
Branching logic and activity not working

### ISSUE THREAD

**Issue by danielmlow** [danielmlow/WellBeingStudy#11]
Protocol: https://danielmlow.github.io/WellBeingStudy

Reproschema-library (I'm using a fork): https://github.com/danielmlow/reproschema-library

(1) After audio_check it does not advance to Demographics activity when I click Next. 
![image](https://user-images.githubusercontent.com/14787791/133942700-fc79b922-acfc-4bbb-bf25-729be3c2b829.png)

It just hangs here:
![image](https://user-images.githubusercontent.com/14787791/133942690-6d538f34-2157-4984-932b-730434b07165.png)

If you click on the Demographics activity from the landing page you *can* access it. 

When you finish Demographics activity, it *does* go to the Mental Health activity. So this tells me the issue is in the Demographics activity, right?

(2) Within Demographics activity, for most of the items that have an Other option, it should open a new item "Please specify" only if the person chooses  "Other". However, it *always* goes to the "Other" item (value -1). So if you click on one of the responses, it still goes to the "Other" item (value -1) when it shouldn't
![image](https://user-images.githubusercontent.com/14787791/133942431-5652e4d7-d77e-41cf-9eb3-e59a27ce8344.png)

Here again: 
![image](https://user-images.githubusercontent.com/14787791/133942480-0b0cb068-cd84-448a-bb78-41606566a8ca.png)

So I don't think the item.includes(-1) is working. 

Possible issues: 
* `item.includes(-1)` is not the right way to do it when multipleChoice = true?
* `valueType`: is it supposed to be integer, string, or anyURI? See [here](https://github.com/danielmlow/reproschema-library/blob/f499fdedc2947fc7f586775236e981cc44f10d45/activities/demographics_and_background_information_v1/items/race_ethnicity_global#L9) 
* schemaVersion is rc4? see [here](https://github.com/danielmlow/reproschema-library/blob/f499fdedc2947fc7f586775236e981cc44f10d45/activities/demographics_and_background_information_v1/items/race_ethnicity_global#L4) 
* Are negative values allowed like -1? 

I've played around with this all weekend but can't seem to fix it. 

This is pretty urgent. 

Thanks!

**Comment by sanuann** [comment]
this is fixed now. please check and close the issue.
